/**
 * Curated skill dictionary for the keyword engine (phase 2). Hand-editable —
 * add terms as JDs surface them. Biased toward YJ's domains: gameplay /
 * UE5 / C++, full-stack TS/React/Next, game design, tools/engine work.
 *
 * `name` is the canonical display form; `aliases` are matched case-
 * insensitively after normalization (non-alphanumeric → spaces, so
 * "node.js" also matches "node js"). Multi-word aliases up to 4 words.
 */

export type SkillKind = "hard" | "soft";
export type SkillDef = { name: string; kind: SkillKind; aliases?: string[] };

const H = "hard" as const;
const S = "soft" as const;

export const SKILLS: SkillDef[] = [
  /* ---- game engines & frameworks ---- */
  { name: "Unreal Engine 5", kind: H, aliases: ["ue5", "ue4", "unreal engine", "unreal engine 4", "unreal"] },
  { name: "Unity", kind: H, aliases: ["unity engine", "unity3d", "unity 3d"] },
  { name: "Godot", kind: H },
  { name: "CryEngine", kind: H },
  { name: "Frostbite", kind: H },
  { name: "Source Engine", kind: H, aliases: ["source 2"] },
  { name: "Blueprints", kind: H, aliases: ["blueprint", "ue blueprints", "blueprint scripting"] },
  { name: "Unreal C++", kind: H, aliases: ["unreal engine c++", "ue c++"] },
  { name: "CommonUI", kind: H, aliases: ["common ui"] },
  { name: "UMG", kind: H, aliases: ["unreal motion graphics"] },
  { name: "Slate", kind: H, aliases: ["slate ui"] },
  { name: "Gameplay Ability System", kind: H, aliases: ["gas", "gameplay abilities"] },
  { name: "Behavior Trees", kind: H, aliases: ["behaviour trees", "behavior tree"] },
  { name: "Niagara", kind: H, aliases: ["niagara vfx"] },
  { name: "Chaos Physics", kind: H, aliases: ["chaos"] },
  { name: "Nanite", kind: H },
  { name: "Lumen", kind: H },
  { name: "PhysX", kind: H },
  { name: "Havok", kind: H },
  { name: "MetaSounds", kind: H, aliases: ["metasound"] },
  { name: "Wwise", kind: H },
  { name: "FMOD", kind: H },
  { name: "Phaser", kind: H },
  { name: "PixiJS", kind: H, aliases: ["pixi js", "pixi"] },
  { name: "MonoGame", kind: H },
  { name: "SDL", kind: H, aliases: ["sdl2"] },
  { name: "OpenGL", kind: H },
  { name: "Vulkan", kind: H },
  { name: "DirectX", kind: H, aliases: ["directx 12", "d3d12", "d3d11", "dx12", "dx11"] },
  { name: "Metal", kind: H, aliases: ["metal api"] },
  { name: "WebGL", kind: H },
  { name: "WebGPU", kind: H },
  { name: "Three.js", kind: H, aliases: ["threejs", "three js"] },
  { name: "React Three Fiber", kind: H, aliases: ["r3f"] },
  { name: "Babylon.js", kind: H, aliases: ["babylonjs", "babylon js"] },

  /* ---- game dev domains ---- */
  { name: "Gameplay Programming", kind: H, aliases: ["gameplay programmer", "gameplay engineering", "gameplay engineer", "gameplay systems"] },
  { name: "Game Design", kind: H, aliases: ["game designer", "gameplay design"] },
  { name: "Level Design", kind: H, aliases: ["level designer"] },
  { name: "Systems Design", kind: H, aliases: ["systems designer", "system design"] },
  { name: "Technical Design", kind: H, aliases: ["technical designer"] },
  { name: "Narrative Design", kind: H, aliases: ["narrative designer"] },
  { name: "Economy Design", kind: H, aliases: ["game economy"] },
  { name: "Combat Design", kind: H, aliases: ["combat designer"] },
  { name: "UI Programming", kind: H, aliases: ["ui programmer", "ui engineering", "ui engineer"] },
  { name: "UX Design", kind: H, aliases: ["ux", "user experience", "ux designer"] },
  { name: "UI Design", kind: H, aliases: ["user interface design"] },
  { name: "Engine Programming", kind: H, aliases: ["engine programmer", "engine development", "game engine development"] },
  { name: "Graphics Programming", kind: H, aliases: ["graphics programmer", "rendering engineer", "rendering programmer"] },
  { name: "Rendering", kind: H, aliases: ["renderer", "render pipeline"] },
  { name: "Shaders", kind: H, aliases: ["shader", "hlsl", "glsl", "shader programming"] },
  { name: "Animation Programming", kind: H, aliases: ["animation programmer", "animation systems"] },
  { name: "Physics Programming", kind: H, aliases: ["physics programmer", "physics simulation", "game physics"] },
  { name: "AI Programming", kind: H, aliases: ["ai programmer", "game ai", "npc ai"] },
  { name: "Tools Programming", kind: H, aliases: ["tools programmer", "tools engineer", "tools development", "editor tools"] },
  { name: "Build Engineering", kind: H, aliases: ["build engineer", "build systems", "build pipeline"] },
  { name: "Netcode", kind: H, aliases: ["network programming", "network programmer", "multiplayer programming", "networked gameplay"] },
  { name: "Multiplayer", kind: H, aliases: ["multiplayer games", "online multiplayer"] },
  { name: "Replication", kind: H, aliases: ["net replication"] },
  { name: "Client-Side Prediction", kind: H, aliases: ["client side prediction", "prediction and reconciliation"] },
  { name: "Lag Compensation", kind: H, aliases: ["latency compensation", "server side rewind"] },
  { name: "Dedicated Servers", kind: H, aliases: ["dedicated server", "server hosting"] },
  { name: "Matchmaking", kind: H },
  { name: "Live Ops", kind: H, aliases: ["liveops", "live operations", "live service"] },
  { name: "Procedural Generation", kind: H, aliases: ["procgen", "procedural content"] },
  { name: "Game Feel", kind: H, aliases: ["juice", "game juice"] },
  { name: "Prototyping", kind: H, aliases: ["rapid prototyping", "prototype"] },
  { name: "Playtesting", kind: H, aliases: ["playtests", "playtest", "user testing", "usability testing"] },
  { name: "QA", kind: H, aliases: ["quality assurance", "game testing", "test plans"] },
  { name: "Bug Tracking", kind: H, aliases: ["bug reports", "defect tracking", "triage"] },
  { name: "Localization", kind: H, aliases: ["l10n", "internationalization", "i18n"] },
  { name: "Accessibility", kind: H, aliases: ["a11y", "wcag"] },
  { name: "VR", kind: H, aliases: ["virtual reality", "openxr"] },
  { name: "AR", kind: H, aliases: ["augmented reality", "arkit", "arcore"] },
  { name: "XR", kind: H, aliases: ["mixed reality", "spatial computing"] },
  { name: "Console Development", kind: H, aliases: ["console platforms", "playstation", "xbox", "nintendo switch"] },
  { name: "Mobile Games", kind: H, aliases: ["mobile game development"] },
  { name: "Steam", kind: H, aliases: ["steamworks", "steam sdk"] },
  { name: "Epic Games Store", kind: H, aliases: ["egs", "epic game store"] },
  { name: "Game Publishing", kind: H, aliases: ["publishing", "store pages"] },
  { name: "Monetization", kind: H, aliases: ["in app purchases", "iap", "f2p", "free to play"] },
  { name: "Game Analytics", kind: H, aliases: ["telemetry", "player analytics"] },
  { name: "ECS", kind: H, aliases: ["entity component system", "data oriented design", "dots"] },

  /* ---- languages ---- */
  { name: "C++", kind: H, aliases: ["cpp", "c/c++", "modern c++", "c++17", "c++20", "c++23"] },
  { name: "C", kind: H, aliases: ["c language"] },
  { name: "C#", kind: H, aliases: ["csharp", "c sharp"] },
  { name: "JavaScript", kind: H, aliases: ["js", "es6", "ecmascript"] },
  { name: "TypeScript", kind: H, aliases: ["ts"] },
  { name: "Python", kind: H },
  { name: "Lua", kind: H },
  { name: "Java", kind: H },
  { name: "Kotlin", kind: H },
  { name: "Swift", kind: H },
  { name: "Objective-C", kind: H, aliases: ["objective c", "objc"] },
  { name: "Rust", kind: H },
  // Matched via "golang" only — a bare "go" token false-positives on prose.
  { name: "Golang", kind: H, aliases: ["go lang"] },
  { name: "Ruby", kind: H },
  { name: "PHP", kind: H },
  { name: "SQL", kind: H },
  { name: "GraphQL", kind: H },
  { name: "HTML", kind: H, aliases: ["html5"] },
  { name: "CSS", kind: H, aliases: ["css3"] },
  { name: "Sass", kind: H, aliases: ["scss"] },
  { name: "Bash", kind: H, aliases: ["shell scripting", "shell scripts", "zsh"] },
  { name: "GDScript", kind: H },
  { name: "Assembly", kind: H, aliases: ["asm", "x86 assembly"] },
  { name: "CUDA", kind: H },
  { name: "MATLAB", kind: H },

  /* ---- low-level / CS fundamentals ---- */
  { name: "Data Structures", kind: H, aliases: ["data structures and algorithms", "dsa"] },
  { name: "Algorithms", kind: H, aliases: ["algorithm design"] },
  { name: "Object-Oriented Programming", kind: H, aliases: ["oop", "object oriented programming", "object oriented design"] },
  { name: "Design Patterns", kind: H },
  { name: "Memory Management", kind: H, aliases: ["memory allocation", "memory leaks", "garbage collection"] },
  { name: "Multithreading", kind: H, aliases: ["multi threading", "concurrency", "parallel programming", "thread safety"] },
  { name: "Performance Optimization", kind: H, aliases: ["optimization", "profiling", "performance tuning", "cpu optimization", "gpu optimization"] },
  { name: "Debugging", kind: H, aliases: ["debuggers", "gdb", "lldb", "crash dumps"] },
  { name: "Linear Algebra", kind: H, aliases: ["vector math", "3d math", "matrices", "quaternions"] },
  { name: "Computational Geometry", kind: H, aliases: ["collision detection"] },
  { name: "Operating Systems", kind: H, aliases: ["os internals"] },
  { name: "Computer Graphics", kind: H, aliases: ["3d graphics", "real time rendering"] },
  { name: "Networking", kind: H, aliases: ["tcp/ip", "tcp", "udp", "sockets", "network protocols"] },
  { name: "Distributed Systems", kind: H },
  { name: "Embedded Systems", kind: H, aliases: ["firmware"] },
  { name: "Compilers", kind: H, aliases: ["compiler design", "llvm"] },
  { name: "Computer Science Degree", kind: H, aliases: ["computer science", "cs degree", "bs in computer science"] },

  /* ---- web frontend ---- */
  { name: "React", kind: H, aliases: ["react.js", "reactjs"] },
  { name: "Next.js", kind: H, aliases: ["nextjs", "next js"] },
  { name: "Vue", kind: H, aliases: ["vue.js", "vuejs"] },
  { name: "Angular", kind: H },
  { name: "Svelte", kind: H, aliases: ["sveltekit"] },
  { name: "Tailwind CSS", kind: H, aliases: ["tailwind", "tailwindcss"] },
  { name: "Redux", kind: H },
  { name: "Zustand", kind: H },
  { name: "React Native", kind: H },
  { name: "Expo", kind: H },
  { name: "Flutter", kind: H },
  { name: "Electron", kind: H },
  { name: "Vite", kind: H },
  { name: "Webpack", kind: H },
  { name: "Framer Motion", kind: H, aliases: ["motion.dev", "framer"] },
  { name: "GSAP", kind: H },
  { name: "Responsive Design", kind: H, aliases: ["responsive web design", "mobile first"] },
  { name: "Web Performance", kind: H, aliases: ["core web vitals", "lighthouse"] },
  { name: "Figma", kind: H, aliases: ["figma designs"] },
  { name: "Design Systems", kind: H, aliases: ["component library", "component libraries"] },
  { name: "Storybook", kind: H },

  /* ---- backend / data / cloud ---- */
  { name: "Node.js", kind: H, aliases: ["node", "nodejs"] },
  { name: "Express", kind: H, aliases: ["express.js", "expressjs"] },
  { name: "REST APIs", kind: H, aliases: ["rest", "restful", "rest api", "restful apis", "api design", "web apis"] },
  { name: "WebSockets", kind: H, aliases: ["websocket", "socket.io"] },
  { name: "gRPC", kind: H },
  { name: "Microservices", kind: H, aliases: ["microservice architecture"] },
  { name: "Serverless", kind: H, aliases: ["lambda functions", "edge functions"] },
  { name: "PostgreSQL", kind: H, aliases: ["postgres"] },
  { name: "MySQL", kind: H },
  { name: "SQLite", kind: H },
  { name: "MongoDB", kind: H, aliases: ["mongo"] },
  { name: "NoSQL", kind: H },
  { name: "Redis", kind: H },
  { name: "Supabase", kind: H },
  { name: "Firebase", kind: H, aliases: ["firebase auth", "firestore"] },
  { name: "Prisma", kind: H },
  { name: "Authentication", kind: H, aliases: ["auth", "oauth", "oauth2", "jwt", "sso"] },
  { name: "AWS", kind: H, aliases: ["amazon web services", "ec2", "s3", "aws lambda"] },
  { name: "AWS GameLift", kind: H, aliases: ["gamelift"] },
  { name: "GCP", kind: H, aliases: ["google cloud", "google cloud platform"] },
  { name: "Azure", kind: H, aliases: ["microsoft azure", "playfab"] },
  { name: "Vercel", kind: H, aliases: ["vercel blob"] },
  { name: "Cloudflare", kind: H, aliases: ["cloudflare workers"] },
  { name: "Docker", kind: H, aliases: ["containers", "containerization"] },
  { name: "Kubernetes", kind: H, aliases: ["k8s"] },
  { name: "Terraform", kind: H, aliases: ["infrastructure as code", "iac"] },
  { name: "CI/CD", kind: H, aliases: ["ci cd", "continuous integration", "continuous delivery", "continuous deployment", "build automation"] },
  { name: "GitHub Actions", kind: H },
  { name: "Jenkins", kind: H },
  { name: "Linux", kind: H, aliases: ["unix"] },
  { name: "Nginx", kind: H },
  { name: "Kafka", kind: H },
  { name: "RabbitMQ", kind: H, aliases: ["message queues"] },
  { name: "Elasticsearch", kind: H },
  { name: "Observability", kind: H, aliases: ["monitoring", "logging", "metrics", "grafana", "datadog"] },

  /* ---- AI / ML ---- */
  { name: "Machine Learning", kind: H, aliases: ["ml"] },
  { name: "Deep Learning", kind: H, aliases: ["neural networks"] },
  { name: "PyTorch", kind: H },
  { name: "TensorFlow", kind: H },
  { name: "Computer Vision", kind: H, aliases: ["opencv"] },
  { name: "NLP", kind: H, aliases: ["natural language processing"] },
  { name: "LLMs", kind: H, aliases: ["llm", "large language models", "generative ai", "genai", "gen ai"] },
  { name: "Prompt Engineering", kind: H },
  { name: "RAG", kind: H, aliases: ["retrieval augmented generation", "vector databases", "embeddings"] },
  { name: "AI Agents", kind: H, aliases: ["agentic", "agent frameworks", "mcp"] },
  { name: "Reinforcement Learning", kind: H, aliases: ["rl"] },
  { name: "Data Science", kind: H, aliases: ["pandas", "numpy", "data analysis"] },

  /* ---- tools & pipeline ---- */
  { name: "Git", kind: H, aliases: ["github", "gitlab", "version control", "source control"] },
  { name: "Perforce", kind: H, aliases: ["p4", "p4v", "helix core"] },
  { name: "Plastic SCM", kind: H, aliases: ["unity vcs"] },
  { name: "Jira", kind: H },
  { name: "Confluence", kind: H },
  { name: "Notion", kind: H },
  { name: "Trello", kind: H },
  { name: "Visual Studio", kind: H },
  { name: "VS Code", kind: H, aliases: ["visual studio code"] },
  { name: "Xcode", kind: H },
  { name: "CMake", kind: H },
  { name: "Blender", kind: H },
  { name: "Maya", kind: H, aliases: ["autodesk maya"] },
  { name: "3ds Max", kind: H },
  { name: "Houdini", kind: H },
  { name: "Substance", kind: H, aliases: ["substance painter", "substance designer"] },
  { name: "Photoshop", kind: H, aliases: ["adobe photoshop"] },
  { name: "Aseprite", kind: H, aliases: ["pixel art"] },
  { name: "Miro", kind: H },
  { name: "Excel", kind: H, aliases: ["google sheets", "spreadsheets"] },
  { name: "Unit Testing", kind: H, aliases: ["unit tests", "jest", "pytest", "googletest", "automated testing", "tdd"] },
  { name: "Code Review", kind: H, aliases: ["code reviews", "pull requests"] },
  { name: "Technical Documentation", kind: H, aliases: ["documentation", "design docs", "technical writing"] },
  { name: "Scripting", kind: H, aliases: ["scripting languages", "automation scripts"] },

  /* ---- process ---- */
  { name: "Agile", kind: H, aliases: ["scrum", "sprints", "sprint planning", "kanban"] },
  { name: "Production", kind: H, aliases: ["game production", "producer", "milestones", "roadmap"] },
  { name: "Shipped Titles", kind: H, aliases: ["shipped games", "shipped a game", "shipped title", "launched games"] },

  /* ---- soft skills ---- */
  { name: "Communication", kind: S, aliases: ["communication skills", "written communication", "verbal communication"] },
  { name: "Collaboration", kind: S, aliases: ["collaborative", "cross functional", "cross discipline", "interdisciplinary", "team player", "teamwork"] },
  { name: "Leadership", kind: S, aliases: ["leading teams", "team lead", "mentorship", "mentoring", "mentor"] },
  { name: "Problem Solving", kind: S, aliases: ["problem solver", "analytical skills", "critical thinking"] },
  { name: "Self-Starter", kind: S, aliases: ["self starter", "self motivated", "self directed", "proactive", "initiative", "autonomy", "autonomous"] },
  { name: "Adaptability", kind: S, aliases: ["adaptable", "flexibility", "fast paced", "fast learner", "quick learner", "learning mindset"] },
  { name: "Attention to Detail", kind: S, aliases: ["detail oriented", "meticulous"] },
  { name: "Creativity", kind: S, aliases: ["creative", "creative problem solving"] },
  { name: "Passion for Games", kind: S, aliases: ["passion for gaming", "love of games", "passionate about games", "gamer"] },
  { name: "Ownership", kind: S, aliases: ["accountability", "end to end ownership"] },
  { name: "Time Management", kind: S, aliases: ["prioritization", "deadlines", "organized", "organizational skills"] },
  { name: "Curiosity", kind: S, aliases: ["curious", "growth mindset", "eager to learn"] },
  { name: "Empathy", kind: S, aliases: ["player empathy", "user empathy", "player first"] },
  { name: "Feedback", kind: S, aliases: ["receiving feedback", "iterate on feedback", "iteration"] },
  { name: "Presentation", kind: S, aliases: ["presenting", "public speaking", "pitching"] },
];
